### ISSUE TITLE
PowerJQL some time fails in Jira Service Desk 

### ISSUE THREAD

**Issue by MikhailChurov** [proficient-developer/Power-JQL#3]
Hi Team!

We tried to use your plugin in IF condition in JIra Service Desk Automation rule, but we see that some times it doesn`t work
JQL we use: issue in powerIssue("project=MSO AND reporter in (icinga.integration) AND resolution = Unresolved AND created > -5m", "summary", ".(WARNING|CRITICAL|DOWN|UNREACHABLE|UNKNOWN).")

Have you faced this kind of issue?

**Comment by proficient-developer** [comment]
Could you please provide more details, when it works properly and when it doesn't?

**Comment by proficient-developer** [comment]
Fixed in release 1.0.7
